name: children_education
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  animate_do: ^3.0.2
  audioplayers: ^4.1.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/splash_images/
    - assets/home_images/
    - assets/ar_image/
    - assets/numbers_eng_image/
    - assets/numbers_ar_image/
    - assets/eng_image/
    - assets/ar_sound/
    - assets/letters_eng_sound/
    - assets/numbers_ar_sound/
    - assets/numbers_eng_sound/
    - assets/animals_images/
    - assets/animals_sound/

  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
